# Information extraction with LLMs
direction: right

classes: {
  node: {
    style: {
      font-size: 36
    }
  }
  edge: {
    style: {
      font-size: 36
      font-color: black
    }
  }
}

vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 300
  }
}

Input Text: {
  class: node
  shape: rectangle
}

LLM: {
  class: node
  shape: rectangle
  icon: https://icons.terrastruct.com/aws%2FMachine%20Learning%2FAmazon-SageMaker_Model_light-bg.svg
}

Few-shot examples: {
  class: node
  shape: rectangle
  style: {
    multiple: true
  }
}

Prompt: {
  class: node
  shape: rectangle
}

Output Schema: {
  class: node
  shape: rectangle
}

Structured Output: {
  class: node
  shape: rectangle
}

# Define connections
Input Text -> LLM: {
  class: edge
}
Few-shot examples -> Prompt: {
  class: edge
}
Prompt -> LLM: {
  class: edge
}
Output Schema -> LLM: {
  class: edge
}
LLM -> Structured Output: {
  class: edge
}
